import { Listing, User } from '@/lib/types';

function createOwner(
  id: string,
  email: string,
  createdAt: string,
  profileId: string,
  fullName: string,
  displayName: string,
): User {
  return {
    id,
    email,
    role: 'USER',
    status: 'ACTIVE',
    created_at: createdAt,
    profile: {
      id: profileId,
      full_name: fullName,
      display_name: displayName,
    },
  };
}

export const MOCK_LISTINGS: Listing[] = [
  {
    id: 'listing-1',
    owner_id: 'user-1',
    category_id: 'cat-1',
    title: 'MacBook Pro 14" 2023 - Excellent condition',
    description: 'Barely used MacBook Pro 14 inch, M2 Pro chip, 512GB SSD, 16GB RAM',
    price: '35000000',
    condition: 'LIKE_NEW',
    brand: 'Apple',
    has_warranty: true,
    location_data: { lat: 21.0285, lng: 105.8542, address: 'Hà Nội, Việt Nam' },
    image_urls: ['https://via.placeholder.com/300?text=MacBook+Pro'],
    status: 'AVAILABLE',
    created_at: '2026-05-10T10:30:00Z',
    owner: createOwner('user-1', 'seller1@example.com', '2026-01-01T00:00:00Z', 'prof-1', 'Nguyễn Văn A', 'NVA'),
  },
  {
    id: 'listing-2',
    owner_id: 'user-2',
    category_id: 'cat-2',
    title: 'Áo phông Supreme - Size M',
    description: 'Áo phông Supreme authentic, còn mới 95%',
    price: '800000',
    condition: 'USED',
    brand: 'Supreme',
    has_warranty: false,
    location_data: { lat: 21.0285, lng: 105.8542, address: 'Hà Nội, Việt Nam' },
    image_urls: ['https://via.placeholder.com/300?text=T-Shirt'],
    status: 'AVAILABLE',
    created_at: '2026-05-11T15:45:00Z',
    owner: createOwner('user-2', 'seller2@example.com', '2026-02-01T00:00:00Z', 'prof-2', 'Trần Thị B', 'TTB'),
  },
  {
    id: 'listing-3',
    owner_id: 'user-3',
    category_id: 'cat-3',
    title: 'Xe đạp fixed gear - Trắng',
    description: 'Xe đạp fixed gear chất lượng cao, khung nhôm, bánh 700c',
    price: '5500000',
    condition: 'USED',
    brand: 'NoName',
    has_warranty: false,
    location_data: { lat: 21.0285, lng: 105.8542, address: 'Hà Nội, Việt Nam' },
    image_urls: ['https://via.placeholder.com/300?text=Fixed+Gear'],
    status: 'RESERVED',
    created_at: '2026-05-09T08:20:00Z',
    owner: createOwner('user-3', 'seller3@example.com', '2026-03-01T00:00:00Z', 'prof-3', 'Lê Văn C', 'LVC'),
  },
  {
    id: 'listing-4',
    owner_id: 'user-4',
    category_id: 'cat-4',
    title: 'Kính mát Ray-Ban - Authentic',
    description: 'Kính mát Ray-Ban chính hãng, hộp và giấy tờ đầy đủ',
    price: '2800000',
    condition: 'NEW',
    brand: 'Ray-Ban',
    has_warranty: true,
    location_data: { lat: 21.0285, lng: 105.8542, address: 'Hà Nội, Việt Nam' },
    image_urls: ['https://via.placeholder.com/300?text=Sunglasses'],
    status: 'SOLD',
    created_at: '2026-05-08T12:00:00Z',
    owner: createOwner('user-4', 'seller4@example.com', '2026-04-01T00:00:00Z', 'prof-4', 'Phạm Thị D', 'PTD'),
  },
  {
    id: 'listing-5',
    owner_id: 'user-5',
    category_id: 'cat-5',
    title: 'iPhone 12 Pro Max - Space Grey',
    description: 'iPhone 12 Pro Max 128GB, pin còn tốt, không trầy xước',
    price: '18500000',
    condition: 'LIKE_NEW',
    brand: 'Apple',
    has_warranty: false,
    location_data: { lat: 21.0285, lng: 105.8542, address: 'Hà Nội, Việt Nam' },
    image_urls: ['https://via.placeholder.com/300?text=iPhone'],
    status: 'AVAILABLE',
    created_at: '2026-05-12T09:15:00Z',
    owner: createOwner('user-5', 'seller5@example.com', '2026-05-01T00:00:00Z', 'prof-5', 'Hoàng Văn E', 'HVE'),
  },
  {
    id: 'listing-6',
    owner_id: 'user-6',
    category_id: 'cat-6',
    title: 'Giày Nike Air Max 90 - Trắng',
    description: 'Giày Nike Air Max 90 authentic, size 43, đã dùng 2 lần',
    price: '2200000',
    condition: 'LIKE_NEW',
    brand: 'Nike',
    has_warranty: false,
    location_data: { lat: 21.0285, lng: 105.8542, address: 'Hà Nội, Việt Nam' },
    image_urls: ['https://via.placeholder.com/300?text=Nike+Shoes'],
    status: 'AVAILABLE',
    created_at: '2026-05-07T16:30:00Z',
    owner: createOwner('user-6', 'seller6@example.com', '2026-05-02T00:00:00Z', 'prof-6', 'Đỗ Thị F', 'DTF'),
  },
];
