"""add_notifications_and_audit"""
"""add_notifications_and_audit"""

revision = '29b745d20c27'
down_revision = 'b35589f705a5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.models.mixins


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('actor_id', app.models.mixins.SafeUUID(), nullable=True),
    sa.Column('verb', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=255), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('id', app.models.mixins.SafeUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_activity_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_logs'))
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_created_at'), ['created_at'], unique=False)

    op.create_table('notifications',
    sa.Column('recipient_id', app.models.mixins.SafeUUID(), nullable=False),
    sa.Column('type', sa.Enum('OFFER_RECEIVED', 'OFFER_ACCEPTED', 'OFFER_DECLINED', 'OFFER_COUNTERED', 'DEAL_COMPLETED', 'DEAL_CANCELLED', 'MEETUP_SCHEDULED', 'MEETUP_COMPLETED', 'REPORT_RESOLVED', 'SYSTEM', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', app.models.mixins.SafeUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_notifications_recipient_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_recipient_id'), ['recipient_id'], unique=False)

    with op.batch_alter_table('message_deleted_for', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_message_deleted_for_user', ['message_id', 'user_id'])

    with op.batch_alter_table('user_favorite_listing', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_listing_favorite', ['user_id', 'listing_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorite_listing', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_listing_favorite', type_='unique')

    with op.batch_alter_table('message_deleted_for', schema=None) as batch_op:
        batch_op.drop_constraint('uq_message_deleted_for_user', type_='unique')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_actor_id'))

    op.drop_table('activity_logs')
    # ### end Alembic commands ###
