"""Sprint 2: Add Search and Listing fields"""

revision = '5f3ea9cb031e'
down_revision = 'ab07b3324ca1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('slug', sa.String(length=255), nullable=True))
    op.add_column('categories', sa.Column('image_url', sa.String(length=1000), nullable=True))
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.add_column('listings', sa.Column('brand', sa.String(length=255), nullable=True))
    op.add_column('listings', sa.Column('has_warranty', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'has_warranty')
    op.drop_column('listings', 'brand')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_column('categories', 'image_url')
    op.drop_column('categories', 'slug')
    # ### end Alembic commands ###
