"""Sprint 3: Advanced transactions fields"""

revision = '7b19759ade0a'
down_revision = '5f3ea9cb031e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create the new enum delivery_status
    delivery_status = sa.Enum('PENDING', 'SHIPPING', 'DELIVERED', name='delivery_status')
    delivery_status.create(op.get_bind())

    # Add COUNTERED to existing offer_status enum
    op.execute("ALTER TYPE offer_status ADD VALUE IF NOT EXISTS 'COUNTERED'")
    
    op.add_column('deals', sa.Column('delivery_status', delivery_status, server_default='PENDING', nullable=False))
    op.add_column('deals', sa.Column('tracking_code', sa.String(), nullable=True))
    op.add_column('deals', sa.Column('has_dispute', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('deals', sa.Column('dispute_reason', sa.String(), nullable=True))
    op.add_column('meetups', sa.Column('buyer_checked_in', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('meetups', sa.Column('seller_checked_in', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('offers', sa.Column('parent_offer_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=True))
    op.add_column('offers', sa.Column('is_counter_from_seller', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('offers', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(op.f('fk_offers_parent_offer_id_offers'), 'offers', 'offers', ['parent_offer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_offers_parent_offer_id_offers'), 'offers', type_='foreignkey')
    op.drop_column('offers', 'expires_at')
    op.drop_column('offers', 'is_counter_from_seller')
    op.drop_column('offers', 'parent_offer_id')
    op.drop_column('meetups', 'seller_checked_in')
    op.drop_column('meetups', 'buyer_checked_in')
    op.drop_column('deals', 'dispute_reason')
    op.drop_column('deals', 'has_dispute')
    op.drop_column('deals', 'tracking_code')
    op.drop_column('deals', 'delivery_status')
    
    op.execute("DROP TYPE delivery_status")
    # ### end Alembic commands ###
