"""Add Sprint 1 social models and profile fields"""

revision = 'ab07b3324ca1'
down_revision = 'ef0a95542ad9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listing_questions', 'asker_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('listing_questions', 'question',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('listing_questions', 'answer',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_listing_questions_asker_id'), table_name='listing_questions')
    op.drop_index(op.f('ix_listing_questions_listing_id'), table_name='listing_questions')
    op.drop_constraint(op.f('fk_listing_questions_asker_id_users'), 'listing_questions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_listing_questions_asker_id_users'), 'listing_questions', 'users', ['asker_id'], ['id'], ondelete='SET NULL')
    op.drop_column('listing_questions', 'answered_at')
    op.drop_index(op.f('ix_listings_location_data_gin'), table_name='listings', postgresql_using='gin')
    op.add_column('profiles', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('profiles', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('profiles', sa.Column('dob', sa.Date(), nullable=True))
    op.add_column('profiles', sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True))
    op.add_column('profiles', sa.Column('privacy_settings', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True))
    op.add_column('profiles', sa.Column('banner_url', sa.String(length=1024), nullable=True))
    op.add_column('profiles', sa.Column('shop_slug', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_profiles_shop_slug'), 'profiles', ['shop_slug'], unique=True)
    op.alter_column('reviews', 'reviewer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('reviews', 'deal_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('reviews', 'rating',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('reviews', 'comment',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_target_id'), table_name='reviews')
    op.drop_constraint(op.f('uq_reviews_deal_id'), 'reviews', type_='unique')
    op.drop_constraint(op.f('fk_reviews_reviewer_id_users'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('fk_reviews_deal_id_deals'), 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reviews_deal_id_deals'), 'reviews', 'deals', ['deal_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_reviews_reviewer_id_users'), 'reviews', 'users', ['reviewer_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint('uq_user_listing_favorite', 'user_favorite_listing', ['user_id', 'listing_id'])
    op.drop_index(op.f('ix_user_follows_follower_id'), table_name='user_follows')
    op.drop_index(op.f('ix_user_follows_following_id'), table_name='user_follows')
    op.create_unique_constraint('uq_user_follows_follower_following', 'user_follows', ['follower_id', 'following_id'])
    op.drop_index(op.f('ix_wishlist_items_listing_id'), table_name='wishlist_items')
    op.drop_index(op.f('ix_wishlist_items_wishlist_id'), table_name='wishlist_items')
    op.create_unique_constraint('uq_wishlist_items_wishlist_listing', 'wishlist_items', ['wishlist_id', 'listing_id'])
    op.alter_column('wishlists', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_wishlists_user_id'), table_name='wishlists')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_wishlists_user_id'), 'wishlists', ['user_id'], unique=False)
    op.alter_column('wishlists', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_constraint('uq_wishlist_items_wishlist_listing', 'wishlist_items', type_='unique')
    op.create_index(op.f('ix_wishlist_items_wishlist_id'), 'wishlist_items', ['wishlist_id'], unique=False)
    op.create_index(op.f('ix_wishlist_items_listing_id'), 'wishlist_items', ['listing_id'], unique=False)
    op.drop_constraint('uq_user_follows_follower_following', 'user_follows', type_='unique')
    op.create_index(op.f('ix_user_follows_following_id'), 'user_follows', ['following_id'], unique=False)
    op.create_index(op.f('ix_user_follows_follower_id'), 'user_follows', ['follower_id'], unique=False)
    op.drop_constraint('uq_user_listing_favorite', 'user_favorite_listing', type_='unique')
    op.drop_constraint(op.f('fk_reviews_reviewer_id_users'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('fk_reviews_deal_id_deals'), 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reviews_deal_id_deals'), 'reviews', 'deals', ['deal_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_reviews_reviewer_id_users'), 'reviews', 'users', ['reviewer_id'], ['id'], ondelete='RESTRICT')
    op.create_unique_constraint(op.f('uq_reviews_deal_id'), 'reviews', ['deal_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_reviews_target_id'), 'reviews', ['target_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    op.alter_column('reviews', 'comment',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('reviews', 'rating',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.alter_column('reviews', 'deal_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('reviews', 'reviewer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_profiles_shop_slug'), table_name='profiles')
    op.drop_column('profiles', 'shop_slug')
    op.drop_column('profiles', 'banner_url')
    op.drop_column('profiles', 'privacy_settings')
    op.drop_column('profiles', 'social_links')
    op.drop_column('profiles', 'dob')
    op.drop_column('profiles', 'address')
    op.drop_column('profiles', 'phone')
    op.drop_column('profiles', 'display_name')
    op.create_index(op.f('ix_listings_location_data_gin'), 'listings', ['location_data'], unique=False, postgresql_using='gin')
    op.add_column('listing_questions', sa.Column('answered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_listing_questions_asker_id_users'), 'listing_questions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_listing_questions_asker_id_users'), 'listing_questions', 'users', ['asker_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_listing_questions_listing_id'), 'listing_questions', ['listing_id'], unique=False)
    op.create_index(op.f('ix_listing_questions_asker_id'), 'listing_questions', ['asker_id'], unique=False)
    op.alter_column('listing_questions', 'answer',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('listing_questions', 'question',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
    op.alter_column('listing_questions', 'asker_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
