"""add_message_deleted_for"""
"""add_message_deleted_for"""

revision = 'b35589f705a5'
down_revision = 'b639e0dd5b71'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import app.models.mixins



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_deleted_for',
    sa.Column('message_id', app.models.mixins.SafeUUID(), nullable=False),
    sa.Column('user_id', app.models.mixins.SafeUUID(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_deleted_for_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_message_deleted_for_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'user_id', name=op.f('pk_message_deleted_for')),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_message_deleted_for_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_deleted_for')
    # ### end Alembic commands ###
