"""Add OCC version_id column"""

revision = 'b639e0dd5b71'
down_revision = '75d6788d1c8a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('version_id', sa.Integer(), nullable=False))
    op.add_column('listings', sa.Column('version_id', sa.Integer(), nullable=False))
    op.add_column('offers', sa.Column('version_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'version_id')
    op.drop_column('listings', 'version_id')
    op.drop_column('deals', 'version_id')
    # ### end Alembic commands ###
