"""initial schema"""

revision = 'ef0a95542ad9'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=True),
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_index(op.f('ix_categories_created_at'), 'categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_categories_deleted_at'), 'categories', ['deleted_at'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'BANNED', name='user_status'), nullable=False),
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('blocks',
    sa.Column('blocker_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('blocked_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('blocker_id <> blocked_id', name=op.f('ck_blocks_blocker_not_equal_blocked')),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], name=op.f('fk_blocks_blocked_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], name=op.f('fk_blocks_blocker_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blocks')),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='uq_block_pair')
    )
    op.create_index(op.f('ix_blocks_blocked_id'), 'blocks', ['blocked_id'], unique=False)
    op.create_index(op.f('ix_blocks_blocker_id'), 'blocks', ['blocker_id'], unique=False)
    op.create_index(op.f('ix_blocks_created_at'), 'blocks', ['created_at'], unique=False)
    op.create_table('listings',
    sa.Column('owner_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('category_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('condition', sa.Enum('NEW', 'LIKE_NEW', 'USED', 'DAMAGED', name='item_condition'), nullable=False),
    sa.Column('location_data', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'SOLD', 'HIDDEN', name='listing_status'), nullable=False),
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('price >= 0', name=op.f('ck_listings_listing_price_non_negative')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_listings_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_listings_owner_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listings'))
    )
    op.create_index(op.f('ix_listings_created_at'), 'listings', ['created_at'], unique=False)
    op.create_index(op.f('ix_listings_deleted_at'), 'listings', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_listings_owner_id'), 'listings', ['owner_id'], unique=False)
    if op.get_bind().dialect.name == 'postgresql':
        op.execute(
            sa.text(
                'CREATE INDEX IF NOT EXISTS ix_listings_location_data_gin '
                'ON listings USING GIN (location_data)'
            )
        )
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_profiles_user_id'))
    )
    op.create_index(op.f('ix_profiles_created_at'), 'profiles', ['created_at'], unique=False)
    op.create_table('reports',
    sa.Column('reporter_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('target_type', sa.Enum('USER', 'LISTING', 'MESSAGE', name='report_target_type'), nullable=False),
    sa.Column('target_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RESOLVED', 'DISMISSED', name='report_status'), nullable=False),
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_reports_reporter_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_reporter_id'), 'reports', ['reporter_id'], unique=False)
    op.create_table('conversations',
    sa.Column('listing_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_conversations_listing_id_listings'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_deleted_at'), 'conversations', ['deleted_at'], unique=False)
    op.create_table('deals',
    sa.Column('listing_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('buyer_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('seller_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('agreed_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CANCELLED', 'COMPLETED', name='deal_status'), nullable=False),
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('agreed_price >= 0', name=op.f('ck_deals_deal_price_non_negative')),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name=op.f('fk_deals_buyer_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_deals_listing_id_listings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name=op.f('fk_deals_seller_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deals'))
    )
    op.create_index(op.f('ix_deals_buyer_id'), 'deals', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_deals_created_at'), 'deals', ['created_at'], unique=False)
    op.create_index(op.f('ix_deals_listing_id'), 'deals', ['listing_id'], unique=False)
    op.create_index(op.f('ix_deals_seller_id'), 'deals', ['seller_id'], unique=False)
    op.create_table('offers',
    sa.Column('listing_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('buyer_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'CANCELLED', 'EXPIRED', name='offer_status'), nullable=False),
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('price >= 0', name=op.f('ck_offers_offer_price_non_negative')),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name=op.f('fk_offers_buyer_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_offers_listing_id_listings'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offers'))
    )
    op.create_index(op.f('ix_offers_buyer_id'), 'offers', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_offers_created_at'), 'offers', ['created_at'], unique=False)
    op.create_index(op.f('ix_offers_listing_id'), 'offers', ['listing_id'], unique=False)
    op.create_table('user_favorite_listing',
    sa.Column('user_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('listing_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_user_favorite_listing_listing_id_listings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_favorite_listing_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'listing_id', name=op.f('pk_user_favorite_listing')),
    sa.UniqueConstraint('user_id', 'listing_id', name='uq_user_listing_favorite')
    )
    op.create_table('conversation_participant',
    sa.Column('conversation_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_participant_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversation_participant_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', 'user_id', name=op.f('pk_conversation_participant'))
    )
    op.create_table('meetups',
    sa.Column('deal_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', name='meetup_status'), nullable=False),
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_meetups_deal_id_deals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meetups'))
    )
    op.create_index(op.f('ix_meetups_created_at'), 'meetups', ['created_at'], unique=False)
    op.create_index(op.f('ix_meetups_deal_id'), 'meetups', ['deal_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('sender_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('content', sa.String(length=4000), nullable=False),
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_deleted_at'), 'messages', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_deleted_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_meetups_deal_id'), table_name='meetups')
    op.drop_index(op.f('ix_meetups_created_at'), table_name='meetups')
    op.drop_table('meetups')
    op.drop_table('conversation_participant')
    op.drop_table('user_favorite_listing')
    op.drop_index(op.f('ix_offers_listing_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_created_at'), table_name='offers')
    op.drop_index(op.f('ix_offers_buyer_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_deals_seller_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_listing_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_created_at'), table_name='deals')
    op.drop_index(op.f('ix_deals_buyer_id'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_conversations_deleted_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_reports_reporter_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_profiles_created_at'), table_name='profiles')
    op.drop_table('profiles')
    if op.get_bind().dialect.name == 'postgresql':
        op.execute(sa.text('DROP INDEX IF EXISTS ix_listings_location_data_gin'))
    op.drop_index(op.f('ix_listings_owner_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_deleted_at'), table_name='listings')
    op.drop_index(op.f('ix_listings_created_at'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_blocks_created_at'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_blocker_id'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_blocked_id'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_categories_deleted_at'), table_name='categories')
    op.drop_index(op.f('ix_categories_created_at'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
